import test from 'node:test';
import {preview,commitOne} from '../server/asaas-bulk.mjs';
import assert from 'node:assert/strict';
import {cents,dueDate,tokenMatches,statusOf,emit,recover,importPayment,linkCustomer,paymentDetails,applyWebhook,candidates,settlement} from '../server/asaas.mjs';
function database(){const data=new Map();let chain=Promise.resolve();const doc=path=>({path,id:path.split('/').at(-1),get:async()=>snapshot(path),set:async(v,opt)=>{data.set(path,opt?.merge?{...data.get(path),...v}:{...v});},update:async v=>{assert(data.has(path));data.set(path,{...data.get(path),...v});},delete:async()=>data.delete(path)});const snapshot=path=>({id:path.split('/').at(-1),exists:data.has(path),data:()=>data.get(path),ref:doc(path)});return {data,collection:c=>({doc:i=>doc(c+'/'+i),where:(field,op,value)=>({get:async()=>({docs:[...data.keys()].filter(k=>k.startsWith(c+'/')&&data.get(k)[field]===value).map(snapshot)})})}),runTransaction:fn=>{const run=chain.then(()=>fn({get:r=>r.get(),set:(r,v)=>data.set(r.path,{...v}),update:(r,v)=>data.set(r.path,{...data.get(r.path),...v})}));chain=run.catch(()=>{});return run;}};}
async function fixture(fn){const originalFetch=globalThis.fetch;const names=['ASAAS_ENABLED','ASAAS_CREATE_ENABLED','ASAAS_API_KEY','ASAAS_WEBHOOK_TOKEN','VERCEL_ENV'];const previous=Object.fromEntries(names.map(k=>[k,process.env[k]]));Object.assign(process.env,{ASAAS_ENABLED:'true',ASAAS_CREATE_ENABLED:'true',ASAAS_API_KEY:'fake-unit-test-key',ASAAS_WEBHOOK_TOKEN:'a'.repeat(48),VERCEL_ENV:'production'});const db=database();db.data.set('students/s1',{cpf:'529.982.247-25'});db.data.set('financeLogs/f1',{studentId:'s1',amount:'450,00',date:'2030-09-05',status:'PENDENTE',description:'Mensalidade'});db.data.set('se7AsaasCustomers/s1',{customerId:'cus_1'});const remote=new Map();let posts=0,reads=0;let loseReply=false;globalThis.fetch=async(url,options)=>{assert.equal(options.headers.access_token,'fake-unit-test-key');assert(url.startsWith('https://api.asaas.com/v3'));const u=new URL(url),p=u.pathname.replace('/v3','');let result;
 if(p==='/customers/cus_1')result={id:'cus_1',cpfCnpj:'52998224725',name:'Aluno'};
 else if(p==='/customers')result={data:[{id:'cus_1',cpfCnpj:'52998224725',name:'Aluno'}],hasMore:false};
 else if(p==='/payments'&&options.method==='POST'){posts++;const b=JSON.parse(options.body);result={id:'pay_1',...b,status:'PENDING',invoiceUrl:'https://www.asaas.com/i/test'};remote.set(result.id,result);if(loseReply)throw new Error('timeout');}
 else if(p==='/payments'){result={data:[...remote.values()].filter(x=>(!u.searchParams.get('externalReference')||x.externalReference===u.searchParams.get('externalReference'))&&(!u.searchParams.get('customer')||x.customer===u.searchParams.get('customer'))),hasMore:false};}
 else if(p==='/payments/pay_1/pixQrCode')result={encodedImage:'aGVsbG8=',payload:'000201-PIX-TEST',expirationDate:'2030-09-06'};
 else if(p==='/payments/pay_1'){reads++;assert(remote.has('pay_1'));result=remote.get('pay_1');}
 else throw new Error('Unexpected request '+p);return {ok:true,status:200,json:async()=>result};};
 try{await fn({db,remote,posts:()=>posts,reads:()=>reads,loseReply:()=>{loseReply=true;}});}finally{globalThis.fetch=originalFetch;for(const k of names){if(previous[k]===undefined)delete process.env[k];else process.env[k]=previous[k];}}}
test('valores monetários e datas sem confundir minutos ou centavos',()=>{assert.equal(cents('1.234,56'),123456);assert.equal(cents(450),45000);assert.equal(cents('450.10'),45010);for(const value of ['-1','0','1.234','abc'])assert.throws(()=>cents(value));assert.equal(dueDate('05/09/2030'),'2030-09-05');for(const date of ['2030-02-30','2030-99-99','ontem'])assert.throws(()=>dueDate(date));});
test('autenticidade e situações financeiras distintas',()=>{assert(tokenMatches('x'.repeat(40),'x'.repeat(40)));assert(!tokenMatches('incorrect','x'.repeat(40)));assert.equal(statusOf({status:'CONFIRMED'}),'PAGO');assert.equal(statusOf({status:'RECEIVED'}),'PAGO');assert.equal(statusOf({status:'REFUNDED'}),'ESTORNADO (ASAAS)');assert.equal(statusOf({status:'PENDING',deleted:true}),'CANCELADO (ASAAS)');});
test('emissão única, pagamento próprio, Pix e baixa idempotente via consulta autenticada',()=>fixture(async({db,remote,posts,reads})=>{await linkCustomer(db,'s1','',{uid:'master'});await emit(db,'f1','BOLETO',{uid:'master'});await emit(db,'f1','BOLETO',{uid:'master'});assert.equal(posts(),1);await assert.rejects(paymentDetails(db,'f1',{role:'aluno',studentId:'s2'}),/outro aluno/);const qr=await paymentDetails(db,'f1',{role:'aluno',studentId:'s1'});assert.equal(qr.pix.payload,'000201-PIX-TEST');remote.get('pay_1').status='RECEIVED';remote.get('pay_1').paymentDate='2030-09-05';await applyWebhook(db,{id:'evt_test_1',event:'PAYMENT_RECEIVED',payment:{id:'pay_1',value:1}});assert.equal(db.data.get('financeLogs/f1').status,'PAGO');assert.equal(db.data.get('financeLogs/f1').amount,'450,00');const count=reads();await applyWebhook(db,{id:'evt_test_1',event:'PAYMENT_RECEIVED',payment:{id:'pay_1'}});assert.equal(reads(),count);await applyWebhook(db,{id:'evt_partial',event:'PAYMENT_PARTIALLY_REFUNDED',payment:{id:'pay_1'}});assert.equal(db.data.get('financeLogs/f1').status,'ESTORNO PARCIAL (ASAAS)');await assert.rejects(paymentDetails(db,'f1',{role:'aluno',studentId:'s1'}),/conferência/);remote.get('pay_1').status='REFUNDED';await applyWebhook(db,{id:'evt_test_2',event:'PAYMENT_REFUNDED',payment:{id:'pay_1'}});assert.equal(db.data.get('financeLogs/f1').status,'ESTORNADO (ASAAS)');}));
test('resposta perdida nunca gera segunda cobrança; consulta recupera vínculo',()=>fixture(async({db,loseReply,posts})=>{loseReply();await assert.rejects(emit(db,'f1','PIX',{uid:'master'}),/incerta/);assert.equal(db.data.get('se7AsaasInvoices/f1').state,'uncertain');await recover(db,'f1');await emit(db,'f1','PIX',{uid:'master'});assert.equal(posts(),1);}));
test('cobrança existente bloqueia nova emissão e pode ser vinculada sem POST',()=>fixture(async({db,remote,posts})=>{remote.set('pay_1',{id:'pay_1',customer:'cus_1',value:450,dueDate:'2030-09-05',status:'PENDING',billingType:'BOLETO'});const found=await candidates(db,'f1');assert.equal(found.payments[0].matches,true);assert.equal(found.payments[0].alreadyLinked,false);await assert.rejects(emit(db,'f1','BOLETO',{uid:'master'}),/Já existe/);assert(!db.data.has('se7AsaasInvoices/f1'));await importPayment(db,'f1','pay_1',{uid:'master'});assert.equal(posts(),0);assert.equal(db.data.get('financeLogs/f1').asaasPaymentId,'pay_1');}));
test('divergências não dão baixa e cobrança não é ligada a outra fatura',()=>fixture(async({db,remote})=>{await emit(db,'f1','PIX',{uid:'master'});remote.get('pay_1').value=999;remote.get('pay_1').status='RECEIVED';await recover(db,'f1');assert.equal(db.data.get('financeLogs/f1').status,'PENDENTE');assert.equal(db.data.get('financeLogs/f1').asaasReview,true);remote.get('pay_1').value=450;db.data.set('financeLogs/f2',{studentId:'s1',amount:450,date:'2030-09-05',status:'PENDENTE'});await assert.rejects(importPayment(db,'f2','pay_1',{uid:'master'}),/outra fatura/);}));
test('vinculação não cria clientes, CPF divergente é recusado e produção bloqueada em preview',()=>fixture(async({db,posts})=>{db.data.set('students/s1',{cpf:'11144477735'});await assert.rejects(linkCustomer(db,'s1','cus_1',{uid:'master'}),/outro CPF/);assert.equal(posts(),0);process.env.VERCEL_ENV='preview';await assert.rejects(linkCustomer(db,'s1','cus_1',{uid:'master'}),/não ativado/);}));

 test('lote: prévia, confirmação sem emissão, repetição, alteração e permissões do plano',()=>fixture(async({db,remote,posts})=>{remote.set('pay_1',{id:'pay_1',customer:'cus_1',value:450,dueDate:'2030-09-05',status:'PENDING',billingType:'BOLETO'});const p=await preview(db,'s1',{uid:'master'});assert.equal(p.ready,1);assert.equal(posts(),0);await assert.rejects(commitOne(db,p.planId,'f1',{uid:'other'}),/autorizada/);db.data.get('financeLogs/f1').date='2030-09-06';await assert.rejects(commitOne(db,p.planId,'f1',{uid:'master'}),/alterada/);db.data.get('financeLogs/f1').date='2030-09-05';await commitOne(db,p.planId,'f1',{uid:'master'});await commitOne(db,p.planId,'f1',{uid:'master'});assert.equal(posts(),0);assert.equal((await preview(db,'s1',{uid:'master'})).rows[0].result,'already');}));
 test('lote: duplicidades locais ou remotas não viram correspondência pronta',()=>fixture(async({db,remote})=>{remote.set('pay_1',{id:'pay_1',customer:'cus_1',value:450,dueDate:'2030-09-05',status:'PENDING'});db.data.set('financeLogs/f2',{studentId:'s1',amount:450,date:'2030-09-05',status:'PENDENTE'});let p=await preview(db,'s1',{uid:'master'});assert.equal(p.ready,0);assert(p.rows.every(r=>r.result==='ambiguous'));db.data.delete('financeLogs/f2');remote.set('pay_duplicate',{id:'pay_duplicate',customer:'cus_1',value:450,dueDate:'2030-09-05',status:'PENDING'});p=await preview(db,'s1',{uid:'master'});assert.equal(p.ready,0);assert.equal(p.rows[0].result,'ambiguous');}));

test('valor pago real separa desconto, acréscimos e tarifas',()=>{let p=settlement({status:'RECEIVED',originalValue:270,value:250,netValue:247});assert.equal(p.paidValueCents,25000);assert.equal(p.discountCents,2000);assert.equal(p.surchargeCents,0);p=settlement({status:'CONFIRMED',originalValue:270,value:280,interestValue:10});assert.equal(p.paidValueCents,28000);assert.equal(p.surchargeCents,1000);assert.equal(p.discountCents,0);assert.equal(settlement({status:'PENDING',value:270}).paidValueCents,null);});
test('sincronização grava valor pago e desconto sem modificar mensalidade',()=>fixture(async({db,remote})=>{await emit(db,'f1','BOLETO',{uid:'master'});Object.assign(remote.get('pay_1'),{status:'RECEIVED',originalValue:450,value:400,netValue:395,clientPaymentDate:'2030-09-04',paymentDate:'2030-09-06'});await recover(db,'f1');const f=db.data.get('financeLogs/f1');assert.equal(f.amount,'450,00');assert.equal(f.asaasPaidValueCents,40000);assert.equal(f.asaasDiscountCents,5000);assert.equal(f.asaasNetValue,395);assert.equal(f.dataPagamento,'2030-09-04');}));

test('recibo usa identificação do aluno autorizado e URLs confiáveis sem nova emissão',()=>fixture(async({db,remote,posts})=>{db.data.get('students/s1').fullname='Aluno Exemplo';await emit(db,'f1','BOLETO',{uid:'master'});Object.assign(remote.get('pay_1'),{status:'RECEIVED',paymentDate:'2030-09-05',transactionReceiptUrl:'https://www.asaas.com/comprovantes/test'});const r=await paymentDetails(db,'f1',{role:'aluno',studentId:'s1'});assert.equal(r.receipt.studentName,'Aluno Exemplo');assert.equal(r.receipt.description,'Mensalidade');assert.equal(r.payment.transactionReceiptUrl,'https://www.asaas.com/comprovantes/test');assert.equal(r.pix,undefined);remote.get('pay_1').transactionReceiptUrl='https://evil.example/receipt';assert.equal((await paymentDetails(db,'f1',{role:'aluno',studentId:'s1'})).payment.transactionReceiptUrl,'');await assert.rejects(paymentDetails(db,'f1',{role:'aluno',studentId:'s2'}),/outro aluno/);assert.equal(posts(),1);}));
