import test from 'node:test';import assert from 'node:assert/strict';
import {emailConfig,calendarSubject,attendanceEmail,gradeEmail,documentsEmail,sendEmail,queuePresence,listEmails,gradeValues,saveGradeWithEmail,saveAttendanceWithEmail,enrollmentEmail} from '../server/email.mjs';
function database(){const data=new Map();let chain=Promise.resolve();const snap=path=>({id:path.split('/').at(-1),exists:data.has(path),data:()=>data.get(path),ref:doc(path)});const doc=path=>({path,id:path.split('/').at(-1),get:async()=>snap(path)});const query=(c,filters=[],order=null,cap=1000)=>({doc:id=>doc(c+'/'+id),where:(k,op,v)=>query(c,[...filters,[k,v]],order,cap),orderBy:(k,dir)=>query(c,filters,[k,dir],cap),limit:n=>query(c,filters,order,n),get:async()=>{let rows=[...data.keys()].filter(k=>k.startsWith(c+'/')&&filters.every(([f,v])=>data.get(k)[f]===v)).map(snap);if(order)rows.sort((a,b)=>String(a.data()[order[0]]).localeCompare(String(b.data()[order[0]]))*(order[1]==='desc'?-1:1));return {docs:rows.slice(0,cap)};}});return {data,collection:c=>query(c),runTransaction:fn=>{const run=chain.then(async()=>{let wrote=false;const changes=[];const result=await fn({get:async r=>{assert.equal(wrote,false,'Firestore reads must precede writes');return r.get();},set:(r,v,opt)=>{wrote=true;changes.push([r.path,v,!!opt?.merge]);},update:(r,v)=>{wrote=true;changes.push([r.path,v,true]);}});for(const [p,v,merge] of changes){const next=merge?structuredClone(data.get(p)||{}):{};for(const [key,value] of Object.entries(v)){const parts=key.split('.');let target=next;for(const part of parts.slice(0,-1)){if(!target[part])target[part]={};target=target[part];}target[parts.at(-1)]=value;}data.set(p,next);}return result;});chain=run.catch(()=>{});return run;}};}
async function fixture(fn){const keys=['SE7_EMAIL_ENABLED','EMAILJS_PRIVATE_KEY','VERCEL_ENV'],old=Object.fromEntries(keys.map(k=>[k,process.env[k]])),fetch=globalThis.fetch;Object.assign(process.env,{SE7_EMAIL_ENABLED:'true',EMAILJS_PRIVATE_KEY:'test-only-private',VERCEL_ENV:'production'});const db=database();db.data.set('students/s1',{fullname:'Aluno Exemplo',status:'Ativo',email:'aluno@example.test',classId:'c1',courseId:'course1',attendance:{'2026-10-10':{status:'Presente'}},grades:{'123':{atividade:'0',avaliacao:'8,5',final:'',salvo:true}},documentos:{}});db.data.set('config/institution',{name:'Instituição SE7'});db.data.set('courses/course1',{name:'Técnico em Enfermagem',subjects:[{id:123,name:'Anatomia'}]});db.data.set('academicCalendars/a1',{classId:'c1',dates:['2026-10-10'],subject:'Anatomia'});db.data.set('attendanceRecords/r1',{classId:'c1',date:'2026-10-10',emailSubject:'Anatomia',frequencias:[{studentId:'s1',status:'Presente'}]});let calls=0,mode='ok',bodies=[];globalThis.fetch=async(url,opts)=>{calls++;assert.equal(url,'https://api.emailjs.com/api/v1.0/email/send');bodies.push(JSON.parse(opts.body));if(mode==='timeout')throw Error('timeout');return {ok:mode==='ok',status:mode==='ok'?200:400};};try{await fn({db,calls:()=>calls,bodies,mode:m=>mode=m});}finally{globalThis.fetch=fetch;for(const k of keys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}}}
const staff={role:'master',uid:'master'};
test('presença lê calendário e banco, inclui data BR, não avisa falta e deduplica chamada repetida',()=>fixture(async({db,calls,bodies})=>{const a=await attendanceEmail(db,'r1',staff),b=await attendanceEmail(db,'r1',staff);assert.deepEqual(a,b);assert.equal(a.jobs.length,1);const j=db.data.get('se7EmailJobs/'+a.jobs[0]);assert.match(j.params.detalhes,/Anatomia.*10\/10\/2026/);assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'enviado');assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'enviado');assert.equal(calls(),1);assert.equal(bodies[0].accessToken,'test-only-private');assert.equal(bodies[0].template_params.email_aluno,'aluno@example.test');db.data.get('students/s1').attendance['2026-10-10'].status='Falta';assert.equal((await attendanceEmail(db,'r1',staff)).jobs.length,0);}));
test('disciplina ambígua nunca é adivinhada; seleção válida resolve',()=>fixture(async({db,calls})=>{db.data.set('academicCalendars/a2',{classId:'c1',dates:['2026-10-10'],subject:'Biologia'});assert.equal(await calendarSubject(db,'c1','2026-10-10'),'');assert.equal(await calendarSubject(db,'c1','2026-10-10','Biologia'),'Biologia');const id=await queuePresence(db,'s1','2026-10-10','','manual');assert.equal((await sendEmail(db,id,staff)).status,'aguardando_disciplina');assert.equal(calls(),0);}));
test('nota zero e decimal aparecem; repetição não duplica, mudança gera novo aviso e cancela antigo',()=>fixture(async({db,calls})=>{const a=await gradeEmail(db,'s1','123',staff);assert.match(db.data.get('se7EmailJobs/'+a.jobs[0]).params.detalhes,/Atividade: 0; Avaliação: 8,5/);assert.deepEqual(await gradeEmail(db,'s1','123',staff),a);db.data.get('students/s1').grades['123'].avaliacao='9';const b=await gradeEmail(db,'s1','123',staff);assert.notDeepEqual(b,a);assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'cancelado');assert.equal((await sendEmail(db,b.jobs[0],staff)).status,'enviado');assert.equal(calls(),1);assert.throws(()=>gradeValues({final:11}),/escala/);}));
test('documentos só avisam conjunto obrigatório com arquivos válidos, sem confundir aprovação',()=>fixture(async({db})=>{const s=db.data.get('students/s1');for(const k of ['rg_cnh','cpf','comprovante_residencia','certidao_nasc_cas','diploma_medio','historico_medio'])s.documentos[k]={status:'Pendente',driveUrl:'https://drive.google.com/file/d/'+k,submissionId:k};s.documentos.cpf.driveUrl='';assert.equal((await documentsEmail(db,'s1')).jobs.length,0);s.documentos.cpf.driveUrl='https://drive.google.com/file/d/cpf';const a=await documentsEmail(db,'s1');assert.equal(a.jobs.length,1);assert.match(db.data.get('se7EmailJobs/'+a.jobs[0]).params.detalhes,/não representa aprovação/);assert.deepEqual(await documentsEmail(db,'s1'),a);s.documentos.cpf.status='Reprovado';assert.equal((await documentsEmail(db,'s1')).jobs.length,0);assert.equal((await sendEmail(db,a.jobs[0],{role:'aluno',studentId:'s1'})).status,'cancelado');}));
test('EJA exige os quatro documentos da modalidade',()=>fixture(async({db})=>{db.data.get('courses/course1').nivel='Supletivo';for(const k of ['rg_cnh','cpf','comprovante_residencia','certidao_nasc_cas'])db.data.get('students/s1').documentos[k]={status:'Aprovado',driveUrl:'https://drive.google.com/'+k};assert.equal((await documentsEmail(db,'s1')).jobs.length,1);}));
test('sem email, email alterado, acesso de outro aluno e financeiro não enviam',()=>fixture(async({db,calls})=>{const a=await gradeEmail(db,'s1','123',staff);await assert.rejects(sendEmail(db,a.jobs[0],{role:'aluno',studentId:'other'}),/outro aluno/);await assert.rejects(gradeEmail(db,'s1','123',{role:'financeiro'}),/restrito/);await assert.rejects(listEmails(db,{role:'aluno'}),/restrito/);db.data.get('students/s1').email='outro@example.test';assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'sem_email');const b=await gradeEmail(db,'s1','123',staff);assert.notDeepEqual(a,b);db.data.get('students/s1').email='';const c=await gradeEmail(db,'s1','123',staff);assert.equal((await sendEmail(db,c.jobs[0],staff)).status,'sem_email');assert.equal(calls(),0);}));
test('concorrência não duplica e falha incerta não é reenviada',()=>fixture(async({db,calls,mode})=>{const a=await gradeEmail(db,'s1','123',staff);mode('timeout');await Promise.all([sendEmail(db,a.jobs[0],staff),sendEmail(db,a.jobs[0],staff)]);assert.equal(calls(),1);assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'conferir');assert.equal(calls(),1);}));
test('limite de um envio por segundo controla chamadas e recusa permite nova tentativa',()=>fixture(async({db,calls,mode})=>{const a=await gradeEmail(db,'s1','123',staff);mode('bad');assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'falha');assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'aguarde');db.data.set('se7EmailControl/rate',{nextAt:0});mode('ok');assert.equal((await sendEmail(db,a.jobs[0],staff)).status,'enviado');assert.equal(calls(),2);}));
test('desativado ou preview não envia nem prepara histórico antigo',()=>fixture(async({db,calls})=>{process.env.SE7_EMAIL_ENABLED='false';assert.equal((await gradeEmail(db,'s1','123',staff)).jobs.length,0);assert.equal((await sendEmail(db,'x',staff)).status,'desativado');process.env.SE7_EMAIL_ENABLED='true';process.env.VERCEL_ENV='preview';assert.equal(emailConfig().enabled,false);assert.equal(calls(),0);}));

test('edição de nota captura valor anterior do banco, não repete e permite voltar ao valor antigo',()=>fixture(async({db})=>{
 const b={studentId:'s1',subjectId:'123',grade:{atividade:'0',avaliacao:'9',final:''}};
 const first=await saveGradeWithEmail(db,b,staff);assert(first.changed);let job=db.data.get('se7EmailJobs/'+first.emailJobs[0]);assert.equal(job.type,'nota_editada');assert.match(job.params.detalhes,/anteriores: Atividade: 0; Avaliação: 8,5.*Novos valores: Atividade: 0; Avaliação: 9/);
 assert.equal(db.data.get('students/s1').grades['123'].avaliacao,'9');const same=await saveGradeWithEmail(db,b,staff);assert.equal(same.changed,false);assert.deepEqual(same.emailJobs,[]);
 b.grade.avaliacao='8.5';const back=await saveGradeWithEmail(db,b,staff);assert(back.changed);assert.notEqual(back.emailJobs[0],first.emailJobs[0]);assert.equal((await sendEmail(db,first.emailJobs[0],staff)).status,'cancelado');
 await assert.rejects(saveGradeWithEmail(db,b,{role:'aluno'}),/restrito/);
}));
test('correção de frequência envia falta e presença, sem repetir turma inalterada',()=>fixture(async({db})=>{
 const b={classId:'c1',date:'2026-10-10',subject:'Anatomia',rows:[{studentId:'s1',status:'Falta'}]};
 const first=await saveAttendanceWithEmail(db,b,staff);let job=db.data.get('se7EmailJobs/'+first.emailJobs[0]);assert.equal(job.type,'frequencia_editada');assert.match(job.params.detalhes,/anterior: Presente.*Nova situação: Falta/);assert.equal(db.data.get('students/s1').attendance[b.date].status,'Falta');assert.equal(db.data.get('attendanceLocks/c1_'+b.date).registros.s1,'Falta');
 assert.deepEqual((await saveAttendanceWithEmail(db,b,staff)).emailJobs,[]);b.rows[0].status='Presente';const back=await saveAttendanceWithEmail(db,b,staff);assert.match(db.data.get('se7EmailJobs/'+back.emailJobs[0]).params.detalhes,/anterior: Falta.*Nova situação: Presente/);assert.equal((await sendEmail(db,first.emailJobs[0],staff)).status,'cancelado');
 b.rows.push({studentId:'s1',status:'Presente'});await assert.rejects(saveAttendanceWithEmail(db,b,staff),/inválidos/);
}));
test('chamada preserva alunos e disciplinas: aluno de outra turma é recusado sem gravar',()=>fixture(async({db})=>{
 const b={classId:'c2',date:'2026-10-10',subject:'Biologia',rows:[{studentId:'s1',status:'Falta'}]};db.data.set('academicCalendars/a2',{classId:'c2',subject:'Biologia',dates:[b.date]});await assert.rejects(saveAttendanceWithEmail(db,b,staff),/nessa turma/);assert.equal(db.data.get('students/s1').attendance[b.date].status,'Presente');
}));
test('nova matrícula exige curso e turma válidos e confirma apenas uma vez',()=>fixture(async({db})=>{
 const s=db.data.get('students/s1');s.status='Ativo';s.code='MAT-2026-TESTE';s.classId='';assert.deepEqual((await enrollmentEmail(db,'s1',staff)).jobs,[]);s.classId='c1';db.data.set('classes/c1',{courseId:'course1',name:'Enfermagem 2026.2'});const first=await enrollmentEmail(db,'s1',staff);assert.equal(first.jobs.length,1);const job=db.data.get('se7EmailJobs/'+first.jobs[0]);assert.equal(job.type,'matricula');assert.match(job.params.detalhes,/MAT-2026-TESTE.*Técnico em Enfermagem.*Enfermagem 2026.2/);assert.deepEqual(await enrollmentEmail(db,'s1',staff),first);s.status='Cancelado';assert.equal((await sendEmail(db,first.jobs[0],staff)).status,'cancelado');await assert.rejects(enrollmentEmail(db,'s1',{role:'professor'}),/confirmar/);
}));
