import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {initializeApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {getAuth} from 'firebase-admin/auth';
import {phoneBR,waConfig,setConsent,enrollmentNotifications,examNotification,sendJob,applyWebhook,verifySignature,listMessages} from '../server/whatsapp.mjs';
import {GET,POST} from '../api/whatsapp-webhook.js';
import {dispatch} from '../api/se7.js';
const app=initializeApp({projectId:'demo-se7-whatsapp'}),db=getFirestore(app),auth=getAuth(app);
const actor={uid:'master-test',role:'master'};
let sequence=0,calls=0;const nativeFetch=globalThis.fetch;
const mockFetch=async()=>{calls++;return Response.json({messages:[{id:'wamid.test.'+(++sequence)}]});};
function configured(){Object.assign(process.env,{WHATSAPP_ENABLED:'true',WHATSAPP_ACCESS_TOKEN:'private-test-token',WHATSAPP_PHONE_NUMBER_ID:'12345',WHATSAPP_API_VERSION:'v26.0',WHATSAPP_APP_SECRET:'test-app-secret',WHATSAPP_VERIFY_TOKEN:'test-verify',WHATSAPP_CENTRAL_PHONE:'5591999990000',WHATSAPP_CENTRAL_OPT_IN:'true'});}
async function student(id){await db.collection('students').doc(id).set({fullname:'Aluno teste',code:'MAT-TEST',courseId:'course',status:'Ativo',whatsapp:'(91) 99999-1234',controleEJA:{dataInicio:'2030-09-05T08:00',dataFim:'2030-09-05T11:00'}});}
function webhook(statuses=[],messages=[],phone='12345'){return {object:'whatsapp_business_account',entry:[{changes:[{value:{metadata:{phone_number_id:phone},statuses,messages}}]}]};}
before(async()=>{configured();await db.collection('courses').doc('course').set({name:'Curso teste'});globalThis.fetch=async(url,options)=>String(url).startsWith('https://graph.facebook.com/')?mockFetch(url,options):nativeFetch(url,options);});
after(async()=>{globalThis.fetch=nativeFetch;await app.delete();});
test('telefone brasileiro e configuração não expõem segredos',()=>{assert.equal(phoneBR('(91) 99999-1234'),'5591999991234');assert.equal(phoneBR('+55 91 99999-1234'),'5591999991234');assert.equal(phoneBR('123'),null);assert(!JSON.stringify(waConfig()).includes('private-test-token'));assert(!JSON.stringify(waConfig()).includes('test-app-secret'));});
test('desativado não envia; aluno exige autorização privada; matrícula não duplica',async()=>{await student('wa1');process.env.WHATSAPP_ENABLED='false';const n=calls;const paused=await enrollmentNotifications(db,'wa1',actor);assert(paused.results.every(x=>x.status==='paused'));assert.equal(calls,n);process.env.WHATSAPP_ENABLED='true';const first=await enrollmentNotifications(db,'wa1',actor);assert.equal(first.results[0].status,'accepted');assert.equal(first.results[1].status,'no_optin');await db.collection('students').doc('wa1').update({whatsappOptIn:true});assert.equal((await sendJob(db,first.results[1].id)).status,'no_optin');await setConsent(db,'wa1',true,actor);assert.equal((await sendJob(db,first.results[1].id)).status,'accepted');const sent=calls;await enrollmentNotifications(db,'wa1',actor);assert.equal(calls,sent);});
test('concorrência adquire uma única tentativa de envio',async()=>{await student('wa2');await setConsent(db,'wa2',true,actor);process.env.WHATSAPP_ENABLED='false';const p=await enrollmentNotifications(db,'wa2',actor);process.env.WHATSAPP_ENABLED='true';let sent=0;const f=async()=>{sent++;await new Promise(r=>setTimeout(r,30));return Response.json({messages:[{id:'wamid.concurrent'}]});};await Promise.all([sendJob(db,p.results[1].id,{fetchImpl:f}),sendJob(db,p.results[1].id,{fetchImpl:f})]);assert.equal(sent,1);});
test('webhook confirma entrega e leitura sem regredir; outro número é ignorado',async()=>{const snap=await db.collection('se7WhatsAppMessages').where('studentId','==','wa1').where('kind','==','student_enrollment').get();const job=snap.docs[0];const id=job.data().metaMessageId;await applyWebhook(db,webhook([{id,status:'delivered',timestamp:'100'}]));assert.equal((await job.ref.get()).data().status,'delivered');await applyWebhook(db,webhook([{id,status:'sent',timestamp:'101'}]));assert.equal((await job.ref.get()).data().status,'delivered');await applyWebhook(db,webhook([{id,status:'read',timestamp:'102'}],[],'wrong'));assert.equal((await job.ref.get()).data().status,'delivered');await applyWebhook(db,webhook([{id,status:'read',timestamp:'103'}]));assert.equal((await job.ref.get()).data().status,'read');});
test('PARAR remove autorização e evita próximas provas; reagendamento cancela aviso antigo',async()=>{await applyWebhook(db,webhook([],[{from:'5591999991234',text:{body:'PARAR'}}]));assert.equal((await db.collection('students').doc('wa1').get()).data().whatsappOptIn,false);const e=await examNotification(db,'wa1',actor);assert.equal(e.results[0].status,'no_optin');await setConsent(db,'wa1',true,actor);await db.collection('students').doc('wa1').update({'controleEJA.dataFim':'2030-09-05T12:00'});assert.equal((await sendJob(db,e.results[0].id)).status,'cancelled');const current=await examNotification(db,'wa1',actor);assert.equal(current.results[0].status,'accepted');});
test('mudança de telefone exige nova autorização e falha ambígua não permite repetição',async()=>{await student('wa3');await setConsent(db,'wa3',true,actor);process.env.WHATSAPP_ENABLED='false';const p=await enrollmentNotifications(db,'wa3',actor);process.env.WHATSAPP_ENABLED='true';await db.collection('students').doc('wa3').update({whatsapp:'91988881234'});assert.equal((await sendJob(db,p.results[1].id)).status,'invalid_phone');await db.collection('students').doc('wa3').update({whatsapp:'91999991234'});const unknown=await sendJob(db,p.results[1].id,{fetchImpl:async()=>{throw new Error('timeout');}});assert.equal(unknown.status,'unknown');let sends=0;await sendJob(db,p.results[1].id,{fetchImpl:async()=>{sends++;}});assert.equal(sends,0);});
test('falha explícita da Meta aparece e pode ser tentada novamente',async()=>{await student('wa4');await setConsent(db,'wa4',true,actor);process.env.WHATSAPP_ENABLED='false';const p=await enrollmentNotifications(db,'wa4',actor);process.env.WHATSAPP_ENABLED='true';assert.equal((await sendJob(db,p.results[1].id,{fetchImpl:async()=>Response.json({error:{code:132001,message:'private detail'}},{status:400})})).status,'failed');const log=await listMessages(db);assert(log.messages.find(x=>x.id===p.results[1].id).error.includes('132001'));assert(!JSON.stringify(log).includes('private detail'));assert.equal((await sendJob(db,p.results[1].id)).status,'accepted');});
test('evento anterior não altera novo envio; confirmação antecipada é preservada',async()=>{await student('wa-race');await setConsent(db,'wa-race',true,actor);process.env.WHATSAPP_ENABLED='false';const p=await enrollmentNotifications(db,'wa-race',actor);process.env.WHATSAPP_ENABLED='true';const jid=p.results[1].id;await sendJob(db,jid,{fetchImpl:async()=>Response.json({messages:[{id:'wamid.old'}]})});await applyWebhook(db,webhook([{id:'wamid.old',status:'failed',timestamp:'100'}]));assert.equal((await db.collection('se7WhatsAppMessages').doc(jid).get()).data().status,'failed');await sendJob(db,jid,{fetchImpl:async()=>{await applyWebhook(db,webhook([{id:'wamid.new',status:'delivered',timestamp:'200'}]));return Response.json({messages:[{id:'wamid.new'}]});}});assert.equal((await db.collection('se7WhatsAppMessages').doc(jid).get()).data().status,'delivered');await applyWebhook(db,webhook([{id:'wamid.old',status:'read',timestamp:'300'}]));assert.equal((await db.collection('se7WhatsAppMessages').doc(jid).get()).data().status,'delivered');});
test('assinatura usa bytes originais; webhook recusa adulteração e valida desafio',async()=>{const raw=JSON.stringify(webhook());const signature='sha256='+createHmac('sha256','test-app-secret').update(raw).digest('hex');assert(verifySignature(Buffer.from(raw),signature,'test-app-secret'));assert(!verifySignature(Buffer.from(raw+' '),signature,'test-app-secret'));assert.equal((await GET(new Request('https://example.test/api?hub.mode=subscribe&hub.verify_token=test-verify&hub.challenge=123'))).status,200);assert.equal((await GET(new Request('https://example.test/api?hub.mode=subscribe&hub.verify_token=wrong&hub.challenge=123'))).status,403);assert.equal((await POST(new Request('https://example.test/api',{method:'POST',headers:{'x-hub-signature-256':signature},body:raw+' '}))).status,403);assert.equal((await POST(new Request('https://example.test/api',{method:'POST',headers:{'x-hub-signature-256':signature},body:raw}))).status,200);});
test('aluno só altera própria autorização; painel e disparos exigem permissão',async()=>{await student('wa-own');await db.collection('students').doc('wa-own').update({se7AuthUid:'wa-user'});const verifiedAuth={verifyIdToken:async()=>({uid:'wa-user',studentId:'wa-own',portalVersion:0})};const req={headers:{authorization:'Bearer verified-fixture'}};await dispatch({auth:verifiedAuth,db},req,{action:'whatsapp-consent',optIn:true});await assert.rejects(dispatch({auth:verifiedAuth,db},req,{action:'whatsapp-consent',id:'wa1',optIn:true}));for(const action of ['whatsapp-list','whatsapp-test','whatsapp-enrollment','whatsapp-exam','whatsapp-retry'])await assert.rejects(dispatch({auth:verifiedAuth,db},req,{action,id:'wa1'}));});
