import {randomBytes,timingSafeEqual} from 'node:crypto';
import {FieldValue as F} from './admin.mjs';
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const id=v=>{if(typeof v!=='string'||!/^[A-Za-z0-9_-]{1,160}$/.test(v))fail(400,'Identificador inválido.');return v;};
export function cents(v){
 const s=typeof v==='number'?String(v):String(v??'').trim().replace(/^R\$\s*/, '');
 const n=s.includes(',')?s.replace(/\./g,'').replace(',','.'):s;
 if(!/^\d+(?:\.\d{1,2})?$/.test(n))fail(400,'Valor inválido. Use no máximo duas casas decimais.');
 const [a,b='']=n.split('.');const c=Number(a)*100+Number(b.padEnd(2,'0'));
 if(!Number.isSafeInteger(c)||c<=0)fail(400,'Valor inválido.');return c;
}
export function dueDate(v){let s=String(v||'');if(/^\d{2}\/\d{2}\/\d{4}$/.test(s))s=s.split('/').reverse().join('-');if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(s+'T12:00:00Z'))||new Date(s+'T12:00:00Z').toISOString().slice(0,10)!==s)fail(400,'Vencimento inválido.');return s;}
export function tokenMatches(a,b){if(typeof a!=='string'||typeof b!=='string'||b.length<32)return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
export function config(){return {environment:'production',configured:!!process.env.ASAAS_API_KEY&&!!process.env.ASAAS_WEBHOOK_TOKEN,enabled:process.env.ASAAS_ENABLED==='true'&&(!process.env.VERCEL_ENV||process.env.VERCEL_ENV==='production'),creationEnabled:process.env.ASAAS_CREATE_ENABLED==='true'};}
export async function api(path,method='GET',body){
 if(!config().enabled||!process.env.ASAAS_API_KEY)fail(503,'Asaas não ativado. Confira as variáveis na Vercel.');
 let r;try{r=await fetch('https://api.asaas.com/v3'+path,{method,headers:{access_token:process.env.ASAAS_API_KEY,'Content-Type':'application/json','User-Agent':'SE7-Gestao-Academica/1.0'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});}catch{fail(503,'Asaas indisponível ou resposta incerta. Não repita a emissão; use Consultar situação.');}
 const d=await r.json().catch(()=>({}));if(!r.ok){const e=Object.assign(new Error(r.status===401?'Chave Asaas recusada. Confira a configuração na Vercel.':'Asaas recusou a operação. Confira os dados e o painel Asaas.'),{status:502,definitive:method==='POST'&&r.status===400});throw e;}return d;
}
async function list(path){const out=[];for(let offset=0;offset<2000;offset+=100){const d=await api(path+(path.includes('?')?'&':'?')+'limit=100&offset='+offset);if(!Array.isArray(d.data))fail(502,'Resposta inesperada do Asaas.');out.push(...d.data);if(!d.hasMore)return out;}fail(409,'Consulta grande demais. Vincule a cobrança pelo identificador.');}
const safeURL=v=>{try{const u=new URL(v);return u.protocol==='https:'&&(u.hostname==='asaas.com'||u.hostname.endsWith('.asaas.com'))?u.href:'';}catch{return '';}};
export function statusOf(p){if(p.deleted)return 'CANCELADO (ASAAS)';return ({RECEIVED:'PAGO',CONFIRMED:'PAGO',RECEIVED_IN_CASH:'PAGO',OVERDUE:'VENCIDO',REFUNDED:'ESTORNADO (ASAAS)',REFUND_REQUESTED:'ESTORNO EM ANÁLISE',REFUND_IN_PROGRESS:'ESTORNO EM ANÁLISE',CHARGEBACK_REQUESTED:'CONTESTADO (ASAAS)',CHARGEBACK_DISPUTE:'CONTESTADO (ASAAS)',AWAITING_CHARGEBACK_REVERSAL:'CONTESTADO (ASAAS)',PENDING:'PENDENTE'})[p.status]||'EM ANÁLISE (ASAAS)';}
const summary=p=>({id:id(p.id),status:p.status||'',value:p.value,dueDate:p.dueDate,invoiceUrl:safeURL(p.invoiceUrl),bankSlipUrl:safeURL(p.bankSlipUrl),billingType:p.billingType||'',paymentDate:p.paymentDate||p.clientPaymentDate||'',creditDate:p.creditDate||'',netValue:p.netValue??null,deleted:p.deleted===true});
async function invoice(db,invoiceId){const r=db.collection('financeLogs').doc(id(invoiceId)),d=await r.get();if(!d.exists)fail(404,'Fatura não encontrada.');const f=d.data();return {ref:r,f,studentId:id(f.studentId||f.alunoId)};}
function eligible(f){if(/PAGO|NEGOCIADO|ACORDO ACEITO|PROPOSTA|AGUARDANDO|CANCELADO|ESTORNADO/i.test(f.status||'')||/PROPOSTA|TERMO DE PROPOSTA/i.test(f.description||f.descricao||''))fail(409,'Essa fatura não pode receber uma nova cobrança.');}
async function customer(db,studentId){const s=await db.collection('students').doc(id(studentId)).get();if(!s.exists)fail(404,'Aluno não encontrado.');const cpf=String(s.data().cpf||'').replace(/\D/g,'');if(cpf.length!==11)fail(400,'Corrija o CPF do aluno no Matriz.');const c=await db.collection('se7AsaasCustomers').doc(studentId).get();if(!c.exists)fail(409,'Vincule primeiro o cliente existente no Asaas.');const d=await api('/customers/'+id(c.data().customerId));if(d.deleted||String(d.cpfCnpj||'').replace(/\D/g,'')!==cpf)fail(409,'O CPF do cliente Asaas não corresponde ao aluno.');return d;}
export async function linkCustomer(db,studentId,customerId,u){
 id(studentId);const s=await db.collection('students').doc(studentId).get();if(!s.exists)fail(404,'Aluno não encontrado.');const cpf=String(s.data().cpf||'').replace(/\D/g,'');if(cpf.length!==11)fail(400,'Corrija o CPF no cadastro do aluno.');
 let d;if(customerId)d=await api('/customers/'+id(customerId));else {const found=(await list('/customers?cpfCnpj='+encodeURIComponent(cpf))).filter(c=>!c.deleted&&String(c.cpfCnpj||'').replace(/\D/g,'')===cpf);if(found.length!==1)fail(409,found.length?'Há mais de um cliente com esse CPF. Informe o ID correto.':'Cliente não encontrado. Cadastre-o no Asaas e depois vincule.');d=found[0];}
 if(d.deleted||String(d.cpfCnpj||'').replace(/\D/g,'')!==cpf)fail(409,'Cliente Asaas pertence a outro CPF.');
 const ref=db.collection('se7AsaasCustomers').doc(studentId);await db.runTransaction(async tx=>{const old=await tx.get(ref);if(old.exists&&old.data().customerId!==d.id)fail(409,'Aluno já vinculado a outro cliente. Confira o cadastro.');tx.set(ref,{customerId:id(d.id),studentId,actor:u.uid,updatedAt:F.serverTimestamp()});});return {customerId:d.id,name:d.name||'Cliente',environment:'production'};
}
// The mapping is reserved before any network mutation. Ambiguous POSTs are never retried automatically.
async function reserve(db,invoiceId,u,mode){const {ref,f,studentId}=await invoice(db,invoiceId);const c=await customer(db,studentId);const map=db.collection('se7AsaasInvoices').doc(invoiceId);const nonce=randomBytes(16).toString('hex');let old;
 await db.runTransaction(async tx=>{const [inv,m]=await Promise.all([tx.get(ref),tx.get(map)]);if(!inv.exists)fail(404,'Fatura removida.');if(m.exists){old=m.data();return;}const fresh=inv.data();eligible(fresh);if((fresh.studentId||fresh.alunoId)!==studentId)fail(409,'Cadastro alterado. Atualize a página.');tx.set(map,{invoiceId,studentId,customerId:c.id,amountCents:cents(fresh.amount??fresh.valor),dueDate:dueDate(fresh.date||fresh.vencimento),externalReference:'se7:'+invoiceId,state:'reserved',mode,nonce,actor:u.uid,createdAt:F.serverTimestamp()});});
 return {map,old,nonce,f};
}
async function attach(db,invoiceId,p,nonce){const map=db.collection('se7AsaasInvoices').doc(id(invoiceId)),reverse=db.collection('se7AsaasPayments').doc(id(p.id));await db.runTransaction(async tx=>{const [m,r]=await Promise.all([tx.get(map),tx.get(reverse)]);if(!m.exists)fail(409,'Vínculo ausente.');const d=m.data();if(nonce&&d.nonce!==nonce)fail(409,'Operação concorrente.');if(d.paymentId&&d.paymentId!==p.id||r.exists&&r.data().invoiceId!==invoiceId)fail(409,'Cobrança já vinculada a outra fatura.');if(p.customer!==d.customerId||cents(p.originalValue??p.value)!==d.amountCents||p.dueDate!==d.dueDate)fail(409,'Cliente, valor ou vencimento não coincide. Confira a cobrança no Asaas.');tx.set(reverse,{invoiceId,studentId:d.studentId});tx.update(map,{paymentId:p.id,state:'linked',updatedAt:F.serverTimestamp()});});return reconcile(db,invoiceId);}
export async function emit(db,invoiceId,type,u){
 if(!config().configured||!config().creationEnabled)fail(503,'Emissão desativada. Ative ASAAS_CREATE_ENABLED na Vercel após configurar o webhook.');if(!['BOLETO','PIX'].includes(type))fail(400,'Escolha boleto ou Pix.');
 const {map,old,nonce,f}=await reserve(db,id(invoiceId),u,'create');if(old)return recover(db,invoiceId);
 const m=(await map.get()).data();try{
  const existing=await list('/payments?customer='+encodeURIComponent(m.customerId));
  const own=existing.filter(p=>p.externalReference===m.externalReference);if(own.length===1)return attach(db,invoiceId,own[0],nonce);if(own.length>1)fail(409,'Cobranças duplicadas no Asaas. Confira antes de continuar.');
  if(existing.some(p=>!p.deleted&&cents(p.originalValue??p.value)===m.amountCents&&p.dueDate===m.dueDate))fail(409,'Já existe cobrança com esse valor e vencimento. Use Buscar cobranças no Asaas.');
  if(m.dueDate<new Date().toLocaleDateString('en-CA',{timeZone:'America/Fortaleza'}))fail(409,'Vencimento passado. Confira a mensalidade antes de emitir.');
  await db.runTransaction(async tx=>{const live=await tx.get(map);if(!live.exists||live.data().nonce!==nonce||live.data().state!=='reserved'||live.data().paymentId)fail(409,'Operação alterada. Consulte a situação.');tx.update(map,{state:'sending',billingType:type});});
  const p=await api('/payments','POST',{customer:m.customerId,billingType:type,value:m.amountCents/100,dueDate:m.dueDate,description:String(f.description||f.descricao||'Mensalidade SE7').slice(0,500),externalReference:m.externalReference});return await attach(db,invoiceId,p,nonce);
 }catch(e){const d=(await map.get()).data();if(d?.nonce===nonce&&!d.paymentId){if(d.state==='reserved'||e.definitive)await map.delete();else await map.update({state:'uncertain',updatedAt:F.serverTimestamp()});}throw e;}
}
export async function importPayment(db,invoiceId,paymentId,u){id(paymentId);const {map,old,nonce}=await reserve(db,id(invoiceId),u,'import');if(old&&!old.paymentId&&old.state!=='uncertain')fail(409,'Há uma operação em andamento. Consulte a emissão antes de vincular.');if(old?.paymentId){if(old.paymentId!==paymentId)fail(409,'Fatura já vinculada a outra cobrança.');return reconcile(db,invoiceId);}try{return await attach(db,invoiceId,await api('/payments/'+paymentId),old?null:nonce);}catch(e){if(!old){const m=(await map.get()).data();if(m?.nonce===nonce&&!m.paymentId)await map.delete();}throw e;}}
export async function recover(db,invoiceId){const m=await db.collection('se7AsaasInvoices').doc(id(invoiceId)).get();if(!m.exists)fail(409,'Fatura ainda não vinculada.');const d=m.data();if(d.paymentId)return reconcile(db,invoiceId);const found=await list('/payments?externalReference='+encodeURIComponent(d.externalReference));if(found.length!==1)fail(409,'Emissão sem confirmação. Confira no painel Asaas e vincule pelo ID. Não emita outra cobrança.');return attach(db,invoiceId,found[0]);}
export async function reconcile(db,invoiceId){const map=db.collection('se7AsaasInvoices').doc(id(invoiceId)),snap=await map.get();if(!snap.exists||!snap.data().paymentId)fail(409,'Cobrança não vinculada.');const m=snap.data();const syncStarted=Date.now();const p=await api('/payments/'+id(m.paymentId));if(p.customer!==m.customerId)fail(409,'Cliente Asaas divergente.');const info=summary(p);const ref=db.collection('financeLogs').doc(invoiceId);
 await db.runTransaction(async tx=>{const [inv,link]=await Promise.all([tx.get(ref),tx.get(map)]);if(!inv.exists)fail(409,'Fatura local removida.');if(!link.exists||link.data().paymentId!==p.id||(inv.data().studentId||inv.data().alunoId)!==m.studentId)fail(409,'Vínculo alterado.');
 if((link.data().syncStarted||0)>syncStarted)return;
 const differs=cents(p.originalValue??p.value)!==m.amountCents||p.dueDate!==m.dueDate||(link.data().partialRefund===true&&p.status!=='REFUNDED');
 tx.update(map,{payment:info,state:differs?'review':'linked',syncStarted,updatedAt:F.serverTimestamp()});
 if(differs){tx.update(ref,{asaasReview:true,asaasStatus:info.status,asaasPaymentId:p.id,...(link.data().partialRefund&&p.status!=='REFUNDED'?{status:'ESTORNO PARCIAL (ASAAS)'}:{})});return;}
 tx.update(ref,{studentId:m.studentId,asaasReview:false,asaasPaymentId:p.id,asaasStatus:info.status,asaasNetValue:info.netValue,asaasCreditDate:info.creditDate,status:statusOf(p),invoiceUrl:info.invoiceUrl,bankSlipUrl:info.bankSlipUrl,dataPagamento:info.paymentDate,formaPagamento:p.billingType==='PIX'?'Pix (Asaas)':p.billingType==='BOLETO'?'Boleto (Asaas)':'Asaas',asaasUpdatedAt:F.serverTimestamp()});});return {payment:info,review:cents(p.originalValue??p.value)!==m.amountCents||p.dueDate!==m.dueDate||(m.partialRefund===true&&p.status!=='REFUNDED')};
}
export async function paymentDetails(db,invoiceId,u){const {studentId}=await invoice(db,invoiceId);if(u.role==='aluno'&&studentId!==u.studentId)fail(403,'Fatura de outro aluno.');const result=await reconcile(db,invoiceId);if(result.review)fail(409,'Cobrança em conferência pelo financeiro.');const p=result.payment;if(!['PENDING','OVERDUE'].includes(p.status)||p.deleted)return result;try{const qr=await api('/payments/'+p.id+'/pixQrCode');return {...result,pix:{encodedImage:typeof qr.encodedImage==='string'&&/^[A-Za-z0-9+/=]+$/.test(qr.encodedImage)&&qr.encodedImage.length<500000?qr.encodedImage:'',payload:String(qr.payload||'').slice(0,5000),expirationDate:qr.expirationDate||''}};}catch{return {...result,pixUnavailable:true};}}
export async function candidates(db,invoiceId){
 const {f,studentId}=await invoice(db,invoiceId);eligible(f);const c=await customer(db,studentId);const value=cents(f.amount??f.valor),date=dueDate(f.date||f.vencimento);const found=await list('/payments?customer='+encodeURIComponent(c.id));const payments=[];
 for(const p of found){if(p.deleted||p.customer!==c.id)continue;const link=await db.collection('se7AsaasPayments').doc(id(p.id)).get();const matches=cents(p.originalValue??p.value)===value&&p.dueDate===date;payments.push({id:p.id,description:String(p.description||'Cobrança').slice(0,500),value:p.originalValue??p.value,dueDate:p.dueDate,status:p.status,matches,alreadyLinked:link.exists&&link.data().invoiceId!==invoiceId});}
 payments.sort((a,b)=>Number(b.matches)-Number(a.matches)||String(b.dueDate).localeCompare(String(a.dueDate)));return {customerName:c.name||'Cliente',invoiceValue:value/100,invoiceDueDate:date,payments};
}
export async function invoices(db,studentId){id(studentId);const [a,b]=await Promise.all([db.collection('financeLogs').where('studentId','==',studentId).get(),db.collection('financeLogs').where('alunoId','==',studentId).get()]);const docs=new Map([...a.docs,...b.docs].map(d=>[d.id,d]));if(docs.size>300)fail(409,'Muitas faturas. Contate o master.');const rows=[];for(const doc of docs.values()){const f=doc.data(),m=await db.collection('se7AsaasInvoices').doc(doc.id).get();rows.push({id:doc.id,description:f.description||f.descricao||'Mensalidade',amount:f.amount??f.valor,date:f.date||f.vencimento||'',status:f.status||'PENDENTE',link:m.exists?{state:m.data().state,paymentId:m.data().paymentId||'',review:m.data().state==='review'}:null});}const key=v=>{try{return dueDate(v);}catch{return '9999-99-99';}};rows.sort((a,b)=>key(a.date).localeCompare(key(b.date))||a.id.localeCompare(b.id));return {invoices:rows};}
export async function applyWebhook(db,payload){if(typeof payload?.id!=='string'||!/^evt_[A-Za-z0-9_-]{1,190}$/.test(payload.id)||typeof payload.event!=='string'||!payload.event.startsWith('PAYMENT_')||typeof payload.payment?.id!=='string')fail(400,'Evento inválido.');const ev=db.collection('se7AsaasEvents').doc(payload.id);const old=await ev.get();if(old.exists&&old.data().processed)return {duplicate:true};const reverse=await db.collection('se7AsaasPayments').doc(id(payload.payment.id)).get();
 if(!reverse.exists){await ev.set({event:payload.event,paymentId:payload.payment.id,processed:false,unmatched:true,receivedAt:F.serverTimestamp()},{merge:true});return {unmatched:true};}
 if(payload.event==='PAYMENT_PARTIALLY_REFUNDED')await db.collection('se7AsaasInvoices').doc(reverse.data().invoiceId).update({partialRefund:true});
 await reconcile(db,reverse.data().invoiceId);await ev.set({event:payload.event,paymentId:payload.payment.id,invoiceId:reverse.data().invoiceId,processed:true,receivedAt:F.serverTimestamp()});return {ok:true};}
