import {createHash,randomBytes} from 'node:crypto';
import {docTypes,validId} from './security.mjs';
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const clean=v=>String(v??'').replace(/[\x00-\x1f<>]/g,' ').trim().slice(0,1000);
const emailOK=v=>typeof v==='string'&&v.length<=254&&/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(v);
export function emailConfig(){const enabled=process.env.SE7_EMAIL_ENABLED==='true'&&(!process.env.VERCEL_ENV||process.env.VERCEL_ENV==='production');const missing=['EMAILJS_PRIVATE_KEY'].filter(k=>!process.env[k]);return {enabled,ready:!missing.length,missing};}
function credentials(){return {service_id:process.env.EMAILJS_SERVICE_ID||'service_hfrg3c8',template_id:process.env.EMAILJS_TEMPLATE_ID||'template_596kbbp',user_id:process.env.EMAILJS_PUBLIC_KEY||'5iKV43-0Y0Tg6_lUk',accessToken:process.env.EMAILJS_PRIVATE_KEY};}
const academic=u=>{if(!['master','secretaria','professor'].includes(u.role))fail(403,'Acesso restrito à equipe acadêmica.');};
async function student(db,id){const d=await db.collection('students').doc(validId(id)).get();if(!d.exists)fail(404,'Aluno não encontrado.');return d.data();}
async function stage(db,id,s,event,key,message,details,status,extra={}){if(!emailConfig().enabled)return null;const institution=(await db.collection('config').doc('institution').get()).data()||{};const address=String(s.email||'').trim();const ref=db.collection('se7EmailJobs').doc(hash([id,event,key,address.toLowerCase()]));await db.runTransaction(async tx=>{const old=await tx.get(ref);if(old.exists)return;tx.set(ref,{studentId:id,studentName:clean(s.fullname||s.name||'Aluno'),type:event,status:status||(!emailOK(address)?'sem_email':'pendente'),email:address,createdAt:new Date().toISOString(),attempts:0,...extra,params:{email_aluno:address,nome_aluno:clean(s.fullname||s.name||'Aluno'),nome_instituicao:clean(institution.name||institution.nome||'Instituição de Ensino SE7'),assunto:'SE7 — '+({presenca:'Presença registrada',documentos:'Documentos recebidos',nota:'Nota lançada'}[event]),titulo:({presenca:'Presença registrada',documentos:'Documentos recebidos',nota:'Nota lançada'}[event]),mensagem:clean(message),detalhes:clean(details)}});});return ref.id;}
export async function calendarSubject(db,classId,date,requested=''){if(!classId||!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return '';const snap=await db.collection('academicCalendars').where('classId','==',classId).get();const names=[...new Set(snap.docs.filter(d=>Array.isArray(d.data().dates)&&d.data().dates.includes(date)).map(d=>clean(d.data().subject)).filter(Boolean))];if(requested&&names.includes(clean(requested)))return clean(requested);return !requested&&names.length===1?names[0]:'';}
export async function queuePresence(db,id,date,subject,source,actorUid=''){const s=await student(db,id);const present=source==='totem'||String(s.attendance?.[date]?.status||'').toLowerCase()==='presente';if(!present)return null;const br=date.split('-').reverse().join('/');return stage(db,id,s,'presenca',[date,subject||'sem-disciplina'],'Sua presença foi registrada.',`Disciplina: ${subject||'Não identificada no calendário'}. Data: ${br}.`,subject?null:'aguardando_disciplina',{date,subject,source,actorUid});}
export async function attendanceEmail(db,recordId,u){academic(u);if(!emailConfig().enabled)return {jobs:[]};const doc=await db.collection('attendanceRecords').doc(validId(recordId)).get();if(!doc.exists)fail(404,'Chamada não encontrada.');const r=doc.data();if(!Array.isArray(r.frequencias)||r.frequencias.length>500)fail(400,'Chamada inválida ou muito extensa.');const subject=await calendarSubject(db,r.classId,r.date,r.emailSubject||'');const ids=[];for(const row of r.frequencias||[]){if(row.status!=='Presente')continue;const s=await student(db,row.studentId);if(s.classId!==r.classId)continue;const id=await queuePresence(db,row.studentId,r.date,subject,'manual',u.uid);if(id)ids.push(id);}return {jobs:ids};}
export function gradeValues(g){const result=[];for(const [key,label] of [['atividade','Atividade'],['avaliacao','Avaliação'],['final','Nota final']]){const v=g?.[key];if(v===null||v===undefined||String(v).trim()==='')continue;const n=Number(String(v).replace(',','.'));if(!Number.isFinite(n)||n<0||n>10)fail(400,'Nota fora da escala de 0 a 10.');result.push([label,n]);}return result;}
export async function gradeEmail(db,id,subjectId,u){academic(u);const s=await student(db,id),key=validId(String(subjectId)),g=s.grades?.[key];if(!g?.salvo)return {jobs:[]};const values=gradeValues(g);if(!values.length)return {jobs:[]};const course=(await db.collection('courses').doc(validId(s.courseId)).get()).data()||{};const subject=course.subjects?.find(x=>String(x.id)===key);if(!subject)fail(409,'Disciplina não encontrada no curso do aluno.');const details=`Disciplina: ${clean(subject.name)}. `+values.map(([label,n])=>`${label}: ${n.toLocaleString('pt-BR',{maximumFractionDigits:2})}`).join('; ')+'.';const job=await stage(db,id,s,'nota',[key,values],'Suas notas foram lançadas. Confira os valores abaixo.',details,null,{subjectId:key,gradeSnapshot:values});return {jobs:job?[job]:[]};}
export async function documentsEmail(db,id){const s=await student(db,id);const course=s.courseId?(await db.collection('courses').doc(validId(s.courseId)).get()).data()||{}:{};const eja=course.nivel==='Supletivo'||course.sigla==='EJA'||String(course.name||'').toUpperCase().includes('EJA');const required=eja?docTypes.filter(x=>!['diploma_medio','historico_medio'].includes(x)):docTypes;const docs=required.map(k=>s.documentos?.[k]);if(!docs.every(d=>d&&['Pendente','Aprovado'].includes(d.status)&&/^https:\/\//.test(d.driveUrl||d.fileUrl||d.url||'')))return {jobs:[]};const fingerprint=docs.map(d=>d.submissionId||d.submittedAt||d.driveUrl||d.fileUrl||d.url);const job=await stage(db,id,s,'documentos',fingerprint,'Recebemos todos os documentos obrigatórios do seu cadastro.','Os documentos estão sujeitos à análise da secretaria. Esta mensagem confirma o recebimento e não representa aprovação.');return {jobs:job?[job]:[]};}
function canSend(u,j){if(u.role==='aluno'){if(u.studentId!==j.studentId||j.type!=='documentos')fail(403,'Aviso de outro aluno.');return;}if(u.role==='totem'){if(j.type!=='presenca'||j.source!=='totem'||j.actorUid!==u.uid)fail(403,'Aviso não permitido ao Totem.');return;}academic(u);}
export async function sendEmail(db,id,u){const cfg=emailConfig();if(!cfg.enabled||!cfg.ready)return {status:'desativado'};const ref=db.collection('se7EmailJobs').doc(validId(id)),gate=db.collection('se7EmailControl').doc('rate');const attempt=randomBytes(12).toString('hex');const reservation=await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)fail(404,'Aviso não encontrado.');const j=snap.data();canSend(u,j);if(!['pendente','falha'].includes(j.status))return {status:j.status};if(j.attempts>=5)return {status:'limite_tentativas'};const current=await tx.get(db.collection('students').doc(j.studentId));const s=current.data();if(!s||!emailOK(s.email)||String(s.email).trim()!==j.email){tx.update(ref,{status:'sem_email',error:'E-mail ausente, inválido ou alterado. Confira o cadastro.'});return {status:'sem_email'};}if(j.type==='nota'&&JSON.stringify(gradeValues(s.grades?.[j.subjectId]))!==JSON.stringify(j.gradeSnapshot)&&j.subjectId){tx.update(ref,{status:'cancelado',error:'Nota alterada após a preparação do aviso.'});return {status:'cancelado'};}if(j.type==='presenca'&&j.source==='manual'&&String(s.attendance?.[j.date]?.status||'').toLowerCase()!=='presente'){tx.update(ref,{status:'cancelado',error:'Presença alterada para falta.'});return {status:'cancelado'};}if(j.type==='documentos'&&Object.values(s.documentos||{}).some(d=>d?.status==='Reprovado')){tx.update(ref,{status:'cancelado',error:'Há documento reprovado após a preparação do aviso.'});return {status:'cancelado'};}const rate=await tx.get(gate),now=Date.now(),next=rate.data()?.nextAt||0;if(next>now)return {status:'aguarde',retryAfterMs:next-now};tx.set(gate,{nextAt:now+1200});tx.update(ref,{status:'enviando',startedAt:new Date().toISOString(),attempt,attempts:(j.attempts||0)+1});return {status:'enviando',job:j};});if(!reservation.job)return reservation;
 let result;try{const res=await fetch('https://api.emailjs.com/api/v1.0/email/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...credentials(),template_params:reservation.job.params}),signal:AbortSignal.timeout(15000)});result=res.ok?{status:'enviado',acceptedAt:new Date().toISOString(),error:''}:{status:res.status>=500?'conferir':'falha',error:`EmailJS recusou o envio (HTTP ${res.status}). Confira conexão, permissão, modelo e limite mensal.`};}catch{result={status:'conferir',error:'Não foi possível confirmar a resposta do serviço. Consulte o Email History no EmailJS antes de repetir.'};}
 await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(snap.data()?.attempt===attempt)tx.update(ref,result);});return {status:result.status};}
export async function listEmails(db,u){if(!['master','secretaria'].includes(u.role))fail(403,'Acesso restrito à secretaria e ao master.');const snap=await db.collection('se7EmailJobs').orderBy('createdAt','desc').limit(100).get();return {config:emailConfig(),jobs:snap.docs.map(d=>{const j=d.data();return {id:d.id,studentName:j.studentName,email:j.email,type:j.type,status:j.status==='enviando'&&Date.now()-Date.parse(j.startedAt)>60000?'conferir':j.status,createdAt:j.createdAt,error:j.error||'',attempts:j.attempts};})};}

export async function pendingEmails(db,u){if(!['master','secretaria'].includes(u.role))fail(403,'Acesso restrito.');const snap=await db.collection('se7EmailJobs').where('status','==','pendente').limit(50).get();return {jobs:snap.docs.map(d=>d.id)};}
