import {createHash,createHmac,timingSafeEqual,randomBytes} from 'node:crypto';
import {FieldValue as F} from './admin.mjs';
const hash=x=>createHash('sha256').update(String(x)).digest('hex');
const jobs='se7WhatsAppMessages',consents='se7WhatsAppConsents';
export const templates={central_enrollment:'se7_aviso_matricula_central',student_enrollment:'se7_matricula_confirmada',student_exam:'se7_prova_agendada'};
export function phoneBR(value){let n=String(value||'').replace(/\D/g,'');if(n.length===10||n.length===11)n='55'+n;return /^55[1-9]\d\d{8,9}$/.test(n)?n:null;}
export function waConfig(){const env=process.env;const required=['WHATSAPP_ACCESS_TOKEN','WHATSAPP_PHONE_NUMBER_ID','WHATSAPP_API_VERSION','WHATSAPP_APP_SECRET','WHATSAPP_VERIFY_TOKEN','WHATSAPP_CENTRAL_PHONE'];const missing=required.filter(k=>!env[k]);if(env.WHATSAPP_PHONE_NUMBER_ID&&!/^\d+$/.test(env.WHATSAPP_PHONE_NUMBER_ID))missing.push('WHATSAPP_PHONE_NUMBER_ID (somente números)');if(env.WHATSAPP_API_VERSION&&!/^v\d+\.\d+$/.test(env.WHATSAPP_API_VERSION))missing.push('WHATSAPP_API_VERSION (ex.: vXX.0)');if(env.WHATSAPP_CENTRAL_PHONE&&!phoneBR(env.WHATSAPP_CENTRAL_PHONE))missing.push('WHATSAPP_CENTRAL_PHONE (55 + DDD + número)');return {enabled:env.WHATSAPP_ENABLED==='true',ready:missing.length===0,missing,centralPhone:phoneBR(env.WHATSAPP_CENTRAL_PHONE),centralOptIn:env.WHATSAPP_CENTRAL_OPT_IN==='true',language:env.WHATSAPP_LANGUAGE||'pt_BR',templates};}
function fault(status,message){throw Object.assign(new Error(message),{status});}
export async function setConsent(db,id,optIn,actor){if(typeof optIn!=='boolean')fault(400,'Informe a autorização para WhatsApp.');const ref=db.collection('students').doc(id),snap=await ref.get();if(!snap.exists)fault(404,'Aluno não encontrado.');const phone=phoneBR(snap.data().whatsapp);if(optIn&&!phone)fault(400,'WhatsApp inválido. Informe DDD e número.');const batch=db.batch();batch.set(db.collection(consents).doc(id),{optIn,phone:phone||'',source:actor.role==='aluno'?'portal':'matriz',actorUid:actor.uid,updatedAt:F.serverTimestamp()});batch.update(ref,{whatsappOptIn:optIn,whatsappOptInAt:new Date().toISOString()});await batch.commit();return {ok:true};}
async function enqueue(db,key,kind,student,to,values,actor){const ref=db.collection(jobs).doc(hash(key));await db.runTransaction(async tx=>{const old=await tx.get(ref);if(old.exists)return;tx.set(ref,{kind,studentId:student?.id||null,to:to||'',values:values.map(v=>String(v||'Não informado').replace(/\s+/g,' ').slice(0,200)),template:templates[kind],status:'pending',attempts:0,createdAt:F.serverTimestamp(),updatedAt:F.serverTimestamp(),actorUid:actor?.uid||'signup'});});return ref.id;}
export async function enrollmentNotifications(db,id,actor){const snap=await db.collection('students').doc(id).get();if(!snap.exists)fault(404,'Aluno não encontrado.');const s={id,...snap.data()};const course=s.courseId?(await db.collection('courses').doc(s.courseId).get()).data():null;const values=[s.fullname,s.code,course?.name||'Curso'];const cfg=waConfig();const ids=[await enqueue(db,'enrollment:central:'+id,'central_enrollment',s,cfg.centralPhone,values,actor),await enqueue(db,'enrollment:student:'+id,'student_enrollment',s,phoneBR(s.whatsapp),values,actor)];const results=[];for(const jobId of ids)results.push(await sendJob(db,jobId));return {results};}
function dateLabel(s){const m=String(s||'').match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]} às ${m[4]}:${m[5]}`:null;}
export async function examNotification(db,id,actor){const snap=await db.collection('students').doc(id).get();if(!snap.exists)fault(404,'Aluno não encontrado.');const s={id,...snap.data()};const start=s.controleEJA?.dataInicio,end=s.controleEJA?.dataFim;if(!dateLabel(start)||!dateLabel(end)||end<=start)fault(400,'O agendamento salvo precisa ter início e término válidos.');const key='exam:'+id+':'+start+':'+end;const jobId=await enqueue(db,key,'student_exam',s,phoneBR(s.whatsapp),[s.fullname,dateLabel(start),dateLabel(end)],actor);return {results:[await sendJob(db,jobId)]};}
async function eligible(db,j,cfg){if(!cfg.enabled||!cfg.ready)return 'paused';if(j.kind==='central_enrollment')return cfg.centralOptIn?'pending':'no_optin';const student=await db.collection('students').doc(j.studentId).get();if(!student.exists||!['Ativo','Ativa'].includes(student.data().status))return 'cancelled';if(j.kind==='student_exam'){const e=student.data().controleEJA||{};if(dateLabel(e.dataInicio)!==j.values[1]||dateLabel(e.dataFim)!==j.values[2]||!(Date.parse(e.dataFim+':00-03:00')>Date.now()))return 'cancelled';}const phone=phoneBR(student.data().whatsapp);if(!phone||phone!==j.to)return 'invalid_phone';const consent=await db.collection(consents).doc(j.studentId).get();return consent.exists&&consent.data().optIn&&consent.data().phone===phone?'pending':'no_optin';}
const retryable=['pending','paused','no_optin','invalid_phone','failed'];
export async function sendJob(db,id,{fetchImpl=fetch}={}){const ref=db.collection(jobs).doc(id);let snap=await ref.get();if(!snap.exists)fault(404,'Mensagem não encontrada.');let j=snap.data();if(!retryable.includes(j.status))return {id,status:j.status};const cfg=waConfig();if(j.kind==='central_enrollment'&&cfg.centralPhone&&j.to!==cfg.centralPhone){j.to=cfg.centralPhone;await ref.update({to:j.to});}const gate=await eligible(db,j,cfg);if(gate!=='pending'){await ref.update({status:gate,updatedAt:F.serverTimestamp()});return {id,status:gate};}
 // Each attempt owns a lease. Ambiguous timeouts never retry automatically.
 const lease=randomBytes(12).toString('hex');const acquired=await db.runTransaction(async tx=>{const d=(await tx.get(ref)).data();if(!retryable.includes(d.status)||d.attempts>=5)return false;tx.update(ref,{status:'sending',lease,attempts:F.increment(1),leaseExpiresAt:new Date(Date.now()+90000),updatedAt:F.serverTimestamp(),error:F.delete(),metaMessageId:F.delete()});return true;});if(!acquired)return {id,status:(await ref.get()).data().status};
 try{const response=await fetchImpl(`https://graph.facebook.com/${process.env.WHATSAPP_API_VERSION}/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:'POST',headers:{Authorization:'Bearer '+process.env.WHATSAPP_ACCESS_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',recipient_type:'individual',to:j.to,type:'template',template:{name:j.template,language:{code:cfg.language},components:[{type:'body',parameters:j.values.map(text=>({type:'text',text}))}]}}),signal:AbortSignal.timeout(15000)});let body;try{body=await response.json();}catch{await ref.update({status:'unknown',error:'O serviço retornou uma resposta inesperada. Confira antes de repetir.',updatedAt:F.serverTimestamp()});return {id,status:'unknown'};}if(!response.ok){const code=Number(body.error?.code)||response.status;await ref.update({status:'failed',error:'Meta recusou a solicitação (código '+code+').',updatedAt:F.serverTimestamp()});return {id,status:'failed'};}const messageId=body.messages?.[0]?.id;if(typeof messageId!=='string'||messageId.length>256){await ref.update({status:'unknown',error:'Resposta sem identificação de mensagem.',updatedAt:F.serverTimestamp()});return {id,status:'unknown'};}
  const map=db.collection('se7WhatsAppMessageIds').doc(hash(messageId));await map.set({jobId:id});await db.runTransaction(async tx=>{const current=(await tx.get(ref)).data();const provider=(await tx.get(db.collection('se7WhatsAppStatuses').doc(hash(messageId)))).data();const status=(ranks[current.status]||0)>(ranks[provider?.status]||1)?current.status:(provider?.status||'accepted');tx.update(ref,{status,metaMessageId:messageId,acceptedAt:F.serverTimestamp(),updatedAt:F.serverTimestamp(),...(provider?.error?{error:provider.error}:{})});});return {id,status:(await ref.get()).data().status};
 }catch{await ref.update({status:'unknown',error:'Sem confirmação do serviço. Confira no WhatsApp antes de repetir.',updatedAt:F.serverTimestamp()});return {id,status:'unknown'};}
}
export async function listMessages(db){const snap=await db.collection(jobs).orderBy('createdAt','desc').limit(50).get();const result=[];for(const d of snap.docs){let j=d.data();if(j.status==='sending'&&j.leaseExpiresAt?.toMillis()<Date.now()){await d.ref.update({status:'unknown',error:'Execução interrompida. Confira antes de repetir.'});j={...j,status:'unknown',error:'Execução interrompida. Confira antes de repetir.'};}result.push({id:d.id,kind:j.kind,to:j.to,status:j.status,attempts:j.attempts,name:j.values?.[0]||'',createdAt:j.createdAt?.toDate().toISOString()||null,error:j.error||''});}return {messages:result};}
export async function checkConnection({fetchImpl=fetch}={}){const cfg=waConfig();if(!cfg.ready)fault(400,'Complete as variáveis: '+cfg.missing.join(', '));const response=await fetchImpl(`https://graph.facebook.com/${process.env.WHATSAPP_API_VERSION}/${process.env.WHATSAPP_PHONE_NUMBER_ID}?fields=display_phone_number,verified_name`,{headers:{Authorization:'Bearer '+process.env.WHATSAPP_ACCESS_TOKEN},signal:AbortSignal.timeout(10000)});const b=await response.json();if(!response.ok)fault(400,'Não foi possível validar o número na Meta. Confira token, permissões e Phone Number ID.');return {ok:true,name:b.verified_name||'',phone:b.display_phone_number||'',note:'Conexão validada. Confira a aprovação dos três modelos no WhatsApp Manager.'};}
export async function centralTest(db,actor){const cfg=waConfig();if(!cfg.enabled||!cfg.ready||!cfg.centralOptIn)fault(400,'Ative a integração e autorize o número da central primeiro.');const id=await enqueue(db,'test:'+randomBytes(12).toString('hex'),'central_enrollment',null,cfg.centralPhone,['Teste SE7','TESTE','Verificação da integração'],actor);return sendJob(db,id);}
export function verifySignature(raw,signature,secret){if(!secret||typeof signature!=='string'||!/^sha256=[a-f0-9]{64}$/.test(signature))return false;const expected=createHmac('sha256',secret).update(raw).digest();return timingSafeEqual(expected,Buffer.from(signature.slice(7),'hex'));}
const ranks={accepted:1,sent:2,failed:2,delivered:3,read:4};
export async function applyWebhook(db,payload){if(payload?.object!=='whatsapp_business_account')return;for(const entry of payload.entry||[])for(const change of entry.changes||[]){const v=change.value;if(!v||String(v.metadata?.phone_number_id)!==process.env.WHATSAPP_PHONE_NUMBER_ID)continue;
 for(const item of v.statuses||[]){if(typeof item.id!=='string'||!ranks[item.status])continue;const ref=db.collection('se7WhatsAppStatuses').doc(hash(item.id));let update;await db.runTransaction(async tx=>{const old=(await tx.get(ref)).data();if(old&&(ranks[old.status]>ranks[item.status]||(ranks[old.status]===ranks[item.status]&&old.timestamp>=Number(item.timestamp))))return;update={status:item.status,timestamp:Number(item.timestamp)||0,error:item.status==='failed'?'Meta informou falha (código '+(Number(item.errors?.[0]?.code)||0)+').':'',updatedAt:F.serverTimestamp()};tx.set(ref,update);});if(update){const map=await db.collection('se7WhatsAppMessageIds').doc(hash(item.id)).get();if(map.exists){const job=db.collection(jobs).doc(map.data().jobId);await db.runTransaction(async tx=>{const current=(await tx.get(job)).data();if(!current||current.metaMessageId!==item.id)return;if((ranks[current.status]||0)>ranks[update.status])return;tx.update(job,{status:update.status,error:update.error,updatedAt:F.serverTimestamp()});});}}}
 for(const message of v.messages||[]){const text=String(message.text?.body||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();if(!['PARAR','SAIR','CANCELAR'].includes(text))continue;const phone=phoneBR(message.from);if(!phone)continue;const snap=await db.collection(consents).where('phone','==',phone).get();for(const d of snap.docs){await d.ref.set({optIn:false,source:'whatsapp_optout',updatedAt:F.serverTimestamp()},{merge:true});const student=db.collection('students').doc(d.id);if((await student.get()).exists)await student.update({whatsappOptIn:false,whatsappOptInAt:new Date().toISOString()});}}
 }}
